/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiketbus;


import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author hp
 */
public class Transaksi extends javax.swing.JFrame {
    private DefaultTableModel model;
    /**
     * Creates new form Transaksi
     */
    public Transaksi() {
        initComponents();
        IdOtomatis();
        this.setLocationRelativeTo(null);
        model = new DefaultTableModel();

        tabeltiket.setModel(model);

        model.addColumn("Id");
        model.addColumn("Nama");
        model.addColumn("Tujuan");
        model.addColumn("Harga");
        model.addColumn("Jumlah");
        model.addColumn("Harga_Total");
        model.addColumn("Diskon");
        model.addColumn("Harga_Bayar");
        loadData();
    }
    public void loadData() {
        btnsimpan.setEnabled(true);
        btnedit.setEnabled(false);
        btndelete.setEnabled(false);
        txtid.setEnabled(false);
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        try {
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();

            String sql = "SELECT * FROM hargatiketbus";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                Object[] o = new Object[8];
                o[0] = r.getString("ID");
                o[1] = r.getString("Nama");
                o[2] = r.getString("Tujuan");
                o[3] = r.getString("Harga");
                o[4] = r.getString("Jumlah");
                o[5] = r.getString("Harga_Total");
                o[6] = r.getString("Diskon");
                o[7] = r.getString("Harga_bayar");
                
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabeltiket = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chkdiskon = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        cmbtujuan = new javax.swing.JComboBox();
        txtharga = new javax.swing.JTextField();
        cmbjumlah = new javax.swing.JComboBox();
        txthargatotal = new javax.swing.JTextField();
        txtdiskon = new javax.swing.JTextField();
        txthargabayar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabeltiket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeltiket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeltiketMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeltiket);

        jLabel1.setText("Id");

        jLabel2.setText("Nama");

        jLabel3.setText("Tujuan");

        jLabel4.setText("Harga");

        jLabel5.setText("Jumlah");

        jLabel6.setText("Harga Total");

        chkdiskon.setText("Diskon 8%");
        chkdiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkdiskonActionPerformed(evt);
            }
        });

        jLabel7.setText("Harga Bayar");

        cmbtujuan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tangerang-Jakarta", "Tangerang-Serang", "Tangerang-Lampung", "Tangerang-Bandung" }));
        cmbtujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtujuanActionPerformed(evt);
            }
        });

        cmbjumlah.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        cmbjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbjumlahActionPerformed(evt);
            }
        });

        jButton1.setText("Bayar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnsimpan.setText("Save");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Impact", 2, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("TRANSAKSI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(chkdiskon))
                                    .addGap(67, 67, 67)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(79, 79, 79))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txtdiskon, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txthargatotal, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtharga, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cmbtujuan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(cmbjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(83, 83, 83)
                                    .addComponent(txthargabayar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(83, 83, 83)
                                        .addComponent(btnsimpan)
                                        .addGap(27, 27, 27)
                                        .addComponent(btnedit)
                                        .addGap(29, 29, 29)
                                        .addComponent(btndelete)
                                        .addGap(28, 28, 28)
                                        .addComponent(btnexit)))
                                .addGap(22, 22, 22))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel1)
                                                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel2))
                                                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3))
                                            .addComponent(cmbtujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4))
                                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addComponent(cmbjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addComponent(txthargatotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkdiskon)
                    .addComponent(txtdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(txthargabayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnsimpan)
                    .addComponent(btndelete)
                    .addComponent(btnexit)
                    .addComponent(btnedit))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void IdOtomatis() {
        try {
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();

            String sql = "SELECT * FROM hargatiketbus ORDER by ID desc";
            ResultSet r = s.executeQuery(sql);

            if (r.next()) {
                String nofak = r.getString("ID").substring(1);
                String AN = "" + (Integer.parseInt(nofak) + 1);
                String Nol = "";

                if (AN.length() == 1) {
                    Nol = "00";
                } else if (AN.length() == 2) {
                    Nol = "0";
                } else if (AN.length() == 3) {
                    Nol = "";
                } 

                txtid.setText("T" + Nol + AN);
            } else {
                txtid.setText("T001");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        {
            int angka1,angka2,hasil;

            //input nilai
            angka1 = Integer.parseInt(txthargatotal.getText());
            angka2 = Integer.parseInt(txtdiskon.getText());

            //rumus
            hasil = angka1 - angka2;

            //output
            txthargabayar.setText(Integer.toString(hasil));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbtujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtujuanActionPerformed
        // TODO add your handling code here:
        String tujuan = null;
        if (cmbtujuan.getSelectedItem()== "Tangerang-Jakarta"){
          txtharga.setText("35000");
        }  
        else if (cmbtujuan.getSelectedItem()== "Tangerang-Serang"){
          txtharga.setText("40000");
        }
         else if (cmbtujuan.getSelectedItem()== "Tangerang-Bandung"){
          txtharga.setText("60000");
        }
        else if (cmbtujuan.getSelectedItem()== "Tangerang-Lampung"){
          txtharga.setText("90000");
        }
    }//GEN-LAST:event_cmbtujuanActionPerformed

    private void cmbjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbjumlahActionPerformed
        // TODO add your handling code here:
        for(int i=1;i<5;i++){
            cmbjumlah.addItem(""+i);
        }
        if (cmbjumlah.getSelectedItem().equals("1")){
            txthargatotal.setText(txtharga.getText());
        }
        else if (cmbjumlah.getSelectedItem().equals("2")){
            int harga = Integer.parseInt(txtharga.getText());
            int total = harga*2 ;
            txthargatotal.setText(Integer.toString(total));
        }
        else if (cmbjumlah.getSelectedItem().equals("3")){
            int harga = Integer.parseInt(txtharga.getText());
            int total = harga*3 ;
            txthargatotal.setText(Integer.toString(total));
        }
        else if (cmbjumlah.getSelectedItem().equals("4")){
            int harga = Integer.parseInt(txtharga.getText());
            int total = harga*4 ;
            txthargatotal.setText(Integer.toString(total));
        }
    }//GEN-LAST:event_cmbjumlahActionPerformed

    private void chkdiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkdiskonActionPerformed
        // TODO add your handling code here:
        if (chkdiskon.isSelected()){
            int total = Integer.parseInt(txtharga.getText());
            int diskon = total*8/100;
            txtdiskon.setText(Integer.toString(diskon));
        }
    }//GEN-LAST:event_chkdiskonActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        MenuUtama au = new MenuUtama();
        au.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        if(txtid.getText().equals("") ||txtnama.getText().equals("") || cmbtujuan.getSelectedItem().toString().equals("")|| txtharga.getText().equals("")|| cmbjumlah.getSelectedItem().toString().equals("")|| txthargatotal.getText().equals("") || txtdiskon.getText().equals("") || txthargabayar.getText().equals("")){
            JOptionPane.showMessageDialog(null, "LENGKAPI DATA !", "elektronik berkah", JOptionPane.INFORMATION_MESSAGE);
        }else{
            String ID = txtid.getText();
            String Nama = txtnama.getText();
            String Tujuan = cmbtujuan.getSelectedItem().toString();
            String Harga = txtharga.getText();
            String Jumlah = cmbjumlah.getSelectedItem().toString();
            String Harga_Total = txthargatotal.getText();
            String Diskon = txtdiskon.getText();
            String Harga_Bayar = txthargabayar.getText();
            
            
            try {
                long millis=System.currentTimeMillis();  
                java.sql.Date date=new java.sql.Date(millis);  
                System.out.println(date); 
                String tgl = date.toString();
                Connection c = koneksi.getKoneksi();

                String sql = "INSERT INTO hargatiketbus VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, ID);
                p.setString(2, Nama);
                p.setString(3, Tujuan);
                p.setString(4, Harga);
                p.setString(5, Jumlah);
                p.setString(6, Harga_Total);
                p.setString(7, Diskon);
                p.setString(8, Harga_Bayar);
                
                p.executeUpdate();
                p.close();
                
            } catch (SQLException e) {
                System.out.println("Terjadi Error");
            } finally {
                loadData();
                IdOtomatis();
                
                txtnama.setText("");
                cmbtujuan.setSelectedItem("");
                txtharga.setText("");
                cmbjumlah.setSelectedItem("");
                txthargatotal.setText("");
                txtdiskon.setText("");
                txthargabayar.setText("");
               
                
                JOptionPane.showMessageDialog(null, "Data berhasil tersimpan", "elekronik berkah", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        if(txtid.getText().equals("") ||txtnama.getText().equals("") || cmbtujuan.getSelectedItem().toString().equals("")|| txtharga.getText().equals("")|| cmbjumlah.getSelectedItem().toString().equals("")|| txthargatotal.getText().equals("") || txtdiskon.getText().equals("") || txthargabayar.getText().equals("")){
            JOptionPane.showMessageDialog(null, "LENGKAPI DATA !", "elektronik berkah", JOptionPane.INFORMATION_MESSAGE);
        }else{
        int i = tabeltiket.getSelectedRow();
        if (i == -1) {
            return;
        }
        String user = (String) model.getValueAt(i, 0);
        try {
            Connection c = koneksi.getKoneksi();
            String sql = "UPDATE  hargatiketbus SET Nama =  '" + txtnama.getText() + "', Tujuan='"+ cmbtujuan.getSelectedItem() + "', Harga='"+ txtharga.getText() + "', Jumlah='"+ cmbjumlah.getSelectedItem() + "', Harga_Total='"+ txthargatotal.getText() + "', Diskon='"+ txtdiskon.getText() + "', Harga_Bayar='"+ txthargabayar.getText()  +"' WHERE  ID ='" + txtid.getText() + "'";
            PreparedStatement p = c.prepareStatement(sql);
            p.executeUpdate();
            p.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error");
        } finally {
            loadData();
                txtid.setText("");
                txtnama.setText("");
                cmbtujuan.setSelectedItem("");
                txtharga.setText("");
                cmbjumlah.setSelectedItem("");
                txthargatotal.setText("");
                txtdiskon.setText("");
                txthargabayar.setText("");
                btnsimpan.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Elektronik Berkah", JOptionPane.INFORMATION_MESSAGE);
        }
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void tabeltiketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeltiketMouseClicked
        // TODO add your handling code here:
        btnsimpan.setEnabled(false);
         btnedit.setEnabled(true);
         btndelete.setEnabled(true);
        int i = tabeltiket.getSelectedRow();
        if (i == -1) {
            return;
        }
        String idtiket = (String) model.getValueAt(i, 0);
        txtid.setText(idtiket);
        txtid.setEnabled(false);

        String nama = (String) model.getValueAt(i, 1);
        txtnama.setText(nama);

        String tujuan = (String) model.getValueAt(i, 2);
        cmbtujuan.setSelectedItem(tujuan);

        String harga = (String) model.getValueAt(i, 3);
        txtharga.setText(harga);

        String jumlah = (String) model.getValueAt(i, 4);
        cmbjumlah.setSelectedItem(jumlah);
        
        String htotal = (String) model.getValueAt(i, 5);
        txthargatotal.setText(htotal);
        
        String diskon = (String) model.getValueAt(i, 6);
        txtdiskon.setText(diskon);
        
        String hbayar = (String) model.getValueAt(i, 7);
        txthargabayar.setText(hbayar);
    }//GEN-LAST:event_tabeltiketMouseClicked

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        try {
            String sql ="delete from hargatiketbus where ID='"+txtid.getText()+"'";
            java.sql.Connection conn=(Connection)koneksi.getKoneksi();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "berhasil di hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        loadData();
        txtid.setText("");
        txtnama.setText("");
        cmbtujuan.setSelectedItem("");
        txtharga.setText("");
        cmbjumlah.setSelectedItem("");
        txthargatotal.setText("");
        txtdiskon.setText("");
        txthargabayar.setText("");
    }//GEN-LAST:event_btndeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JCheckBox chkdiskon;
    private javax.swing.JComboBox cmbjumlah;
    private javax.swing.JComboBox cmbtujuan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabeltiket;
    private javax.swing.JTextField txtdiskon;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txthargabayar;
    private javax.swing.JTextField txthargatotal;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables
}
